
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    user_id serial NOT NULL,
    username character varying(50) COLLATE pg_catalog."default" NOT NULL,
    password character varying(50) COLLATE pg_catalog."default" NOT NULL,
    role character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT USER,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT unique_username UNIQUE (username)
    );

CREATE TABLE IF NOT EXISTS public.words
(
    id integer NOT NULL DEFAULT nextval('words_word_id_seq'::regclass),
    word character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT words_pkey PRIMARY KEY (id)
    );
INSERT INTO words (word) VALUES
                             ('apple'),
                             ('brave'),
                             ('candy'),
                             ('delta'),
                             ('eagle'),
                             ('flame'),
                             ('grape'),
                             ('house'),
                             ('ivory'),
                             ('joker'),
                             ('kneel'),
                             ('lemon'),
                             ('mango'),
                             ('noble'),
                             ('ocean'),
                             ('piano'),
                             ('queen'),
                             ('raven'),
                             ('sheep'),
                             ('tiger'),
                             ('union'),
                             ('vapor'),
                             ('whale'),
                             ('xenon'),
                             ('yacht'),
                             ('zebra'),
                             ('amber'),
                             ('bloom'),
                             ('crane'),
                             ('dream'),
                             ('ember'),
                             ('frost'),
                             ('glory'),
                             ('heart'),
                             ('index'),
                             ('jelly'),
                             ('karma'),
                             ('light'),
                             ('mirth'),
                             ('night'),
                             ('olive'),
                             ('pearl'),
                             ('quilt'),
                             ('rider'),
                             ('stone'),
                             ('trend'),
                             ('ultra'),
                             ('vivid'),
                             ('wrist'),
                             ('xylem'),
                             ('yield'),
                             ('zesty'),
                             ('align'),
                             ('beach'),
                             ('chant'),
                             ('drove'),
                             ('earth'),
                             ('flint'),
                             ('giant'),
                             ('hover'),
                             ('inlet'),
                             ('joust'),
                             ('knife'),
                             ('latch'),
                             ('mimic'),
                             ('ninth'),
                             ('oasis'),
                             ('pouch'),
                             ('quirk'),
                             ('roast'),
                             ('swift'),
                             ('thorn'),
                             ('umbra'),
                             ('vigor'),
                             ('woven'),
                             ('wrath'),
                             ('xerox'),
                             ('young'),
                             ('azure'),
                             ('blaze'),
                             ('charm'),
                             ('drift'),
                             ('feast'),
                             ('grind'),
                             ('haste'),
                             ('inbox'),
                             ('jumpy'),
                             ('knock'),
                             ('loyal'),
                             ('moist'),
                             ('nerdy'),
                             ('orbit'),
                             ('plume'),
                             ('quest'),
                             ('reign'),
                             ('sugar'),
                             ('touch'),
                             ('vowel');
END;